# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.5.1, generator: @autorest/python@5.9.0)
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------
# coding: utf-8

from setuptools import setup, find_packages

NAME = "affinda"
VERSION = "0.1.1"

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["azure-core>=1.16.0"]

setup(
    name=NAME,
    version=VERSION,
    description="Affinda API client for Python",
    author="Affinda",
    author_email="contact@affinda.com",
    url="https://github.com/affinda/affinda-python",
    keywords=["Swagger", "AffindaAPI", "OpenAPI"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    project_urls={
        "Bug Tracker": "https://github.com/affinda/affinda-python/issues",
    },
    long_description="""\
    Affinda API client for Python.
    """,
    python_requires=">=3.6",

)
