# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.1.3, generator: {generator})
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

try:
    from ._request_builders_py3 import build_get_all_resumes_request
    from ._request_builders_py3 import build_create_resume_request
    from ._request_builders_py3 import build_get_resume_request
    from ._request_builders_py3 import build_delete_resume_request
    from ._request_builders_py3 import build_get_all_redacted_resumes_request
    from ._request_builders_py3 import build_create_redacted_resume_request
    from ._request_builders_py3 import build_get_redacted_resume_request
    from ._request_builders_py3 import build_delete_redacted_resume_request
    from ._request_builders_py3 import build_get_all_resume_formats_request
    from ._request_builders_py3 import build_get_all_reformatted_resumes_request
    from ._request_builders_py3 import build_create_reformatted_resume_request
    from ._request_builders_py3 import build_get_reformatted_resume_request
    from ._request_builders_py3 import build_delete_reformatted_resume_request
except (SyntaxError, ImportError):
    from ._request_builders import build_get_all_resumes_request  # type: ignore
    from ._request_builders import build_create_resume_request  # type: ignore
    from ._request_builders import build_get_resume_request  # type: ignore
    from ._request_builders import build_delete_resume_request  # type: ignore
    from ._request_builders import build_get_all_redacted_resumes_request  # type: ignore
    from ._request_builders import build_create_redacted_resume_request  # type: ignore
    from ._request_builders import build_get_redacted_resume_request  # type: ignore
    from ._request_builders import build_delete_redacted_resume_request  # type: ignore
    from ._request_builders import build_get_all_resume_formats_request  # type: ignore
    from ._request_builders import build_get_all_reformatted_resumes_request  # type: ignore
    from ._request_builders import build_create_reformatted_resume_request  # type: ignore
    from ._request_builders import build_get_reformatted_resume_request  # type: ignore
    from ._request_builders import build_delete_reformatted_resume_request  # type: ignore

__all__ = [
    'build_get_all_resumes_request',
    'build_create_resume_request',
    'build_get_resume_request',
    'build_delete_resume_request',
    'build_get_all_redacted_resumes_request',
    'build_create_redacted_resume_request',
    'build_get_redacted_resume_request',
    'build_delete_redacted_resume_request',
    'build_get_all_resume_formats_request',
    'build_get_all_reformatted_resumes_request',
    'build_create_reformatted_resume_request',
    'build_get_reformatted_resume_request',
    'build_delete_reformatted_resume_request',
]
